/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockc_uart3.h"

static const char* CMockString_baudRate = "baudRate";
static const char* CMockString_byte = "byte";
static const char* CMockString_maxLen = "maxLen";
static const char* CMockString_pBuff = "pBuff";
static const char* CMockString_pString = "pString";
static const char* CMockString_rxQSize = "rxQSize";
static const char* CMockString_timeout = "timeout";
static const char* CMockString_timeout_ms = "timeout_ms";
static const char* CMockString_txQSize = "txQSize";
static const char* CMockString_uart3_getchar = "uart3_getchar";
static const char* CMockString_uart3_gets = "uart3_gets";
static const char* CMockString_uart3_init = "uart3_init";
static const char* CMockString_uart3_puts = "uart3_puts";

typedef struct _CMOCK_uart3_getchar_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  bool ReturnVal;
  char* Expected_byte;
  uint32_t Expected_timeout_ms;
  int ReturnThruPtr_byte_Used;
  char* ReturnThruPtr_byte_Val;
  int ReturnThruPtr_byte_Size;
  int IgnoreArg_byte;
  int IgnoreArg_timeout_ms;

} CMOCK_uart3_getchar_CALL_INSTANCE;

typedef struct _CMOCK_uart3_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  bool ReturnVal;
  unsigned int Expected_baudRate;
  int Expected_rxQSize;
  int Expected_txQSize;
  int IgnoreArg_baudRate;
  int IgnoreArg_rxQSize;
  int IgnoreArg_txQSize;

} CMOCK_uart3_init_CALL_INSTANCE;

typedef struct _CMOCK_uart3_gets_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  bool ReturnVal;
  char* Expected_pBuff;
  int Expected_maxLen;
  unsigned int Expected_timeout;
  int ReturnThruPtr_pBuff_Used;
  char* ReturnThruPtr_pBuff_Val;
  int ReturnThruPtr_pBuff_Size;
  int IgnoreArg_pBuff;
  int IgnoreArg_maxLen;
  int IgnoreArg_timeout;

} CMOCK_uart3_gets_CALL_INSTANCE;

typedef struct _CMOCK_uart3_puts_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  bool ReturnVal;
  const char* Expected_pString;
  unsigned int Expected_timeout;
  int IgnoreArg_pString;
  int IgnoreArg_timeout;

} CMOCK_uart3_puts_CALL_INSTANCE;

static struct Mockc_uart3Instance
{
  int uart3_getchar_IgnoreBool;
  bool uart3_getchar_FinalReturn;
  CMOCK_uart3_getchar_CALLBACK uart3_getchar_CallbackFunctionPointer;
  int uart3_getchar_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE uart3_getchar_CallInstance;
  int uart3_init_IgnoreBool;
  bool uart3_init_FinalReturn;
  CMOCK_uart3_init_CALLBACK uart3_init_CallbackFunctionPointer;
  int uart3_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE uart3_init_CallInstance;
  int uart3_gets_IgnoreBool;
  bool uart3_gets_FinalReturn;
  CMOCK_uart3_gets_CALLBACK uart3_gets_CallbackFunctionPointer;
  int uart3_gets_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE uart3_gets_CallInstance;
  int uart3_puts_IgnoreBool;
  bool uart3_puts_FinalReturn;
  CMOCK_uart3_puts_CALLBACK uart3_puts_CallbackFunctionPointer;
  int uart3_puts_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE uart3_puts_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockc_uart3_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.uart3_getchar_IgnoreBool)
    Mock.uart3_getchar_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_uart3_getchar);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart3_getchar_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.uart3_getchar_CallbackFunctionPointer != NULL)
    Mock.uart3_getchar_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.uart3_init_IgnoreBool)
    Mock.uart3_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_uart3_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart3_init_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.uart3_init_CallbackFunctionPointer != NULL)
    Mock.uart3_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.uart3_gets_IgnoreBool)
    Mock.uart3_gets_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_uart3_gets);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart3_gets_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.uart3_gets_CallbackFunctionPointer != NULL)
    Mock.uart3_gets_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.uart3_puts_IgnoreBool)
    Mock.uart3_puts_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_uart3_puts);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart3_puts_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.uart3_puts_CallbackFunctionPointer != NULL)
    Mock.uart3_puts_CallInstance = CMOCK_GUTS_NONE;
}

void Mockc_uart3_Init(void)
{
  Mockc_uart3_Destroy();
}

void Mockc_uart3_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.uart3_getchar_CallbackFunctionPointer = NULL;
  Mock.uart3_getchar_CallbackCalls = 0;
  Mock.uart3_init_CallbackFunctionPointer = NULL;
  Mock.uart3_init_CallbackCalls = 0;
  Mock.uart3_gets_CallbackFunctionPointer = NULL;
  Mock.uart3_gets_CallbackCalls = 0;
  Mock.uart3_puts_CallbackFunctionPointer = NULL;
  Mock.uart3_puts_CallbackCalls = 0;
}

bool uart3_getchar(char* byte, uint32_t timeout_ms)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart3_getchar_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart3_getchar);
  cmock_call_instance = (CMOCK_uart3_getchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart3_getchar_CallInstance);
  Mock.uart3_getchar_CallInstance = CMock_Guts_MemNext(Mock.uart3_getchar_CallInstance);
  if (Mock.uart3_getchar_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.uart3_getchar_FinalReturn;
    Mock.uart3_getchar_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.uart3_getchar_CallbackFunctionPointer != NULL)
  {
    return Mock.uart3_getchar_CallbackFunctionPointer(byte, timeout_ms, Mock.uart3_getchar_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_byte)
  {
    UNITY_SET_DETAILS(CMockString_uart3_getchar,CMockString_byte);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_byte, byte, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_timeout_ms)
  {
    UNITY_SET_DETAILS(CMockString_uart3_getchar,CMockString_timeout_ms);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_timeout_ms, timeout_ms, cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ReturnThruPtr_byte_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(byte, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)byte, (void*)cmock_call_instance->ReturnThruPtr_byte_Val,
      cmock_call_instance->ReturnThruPtr_byte_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart3_getchar(CMOCK_uart3_getchar_CALL_INSTANCE* cmock_call_instance, char* byte, uint32_t timeout_ms)
{
  cmock_call_instance->Expected_byte = byte;
  cmock_call_instance->IgnoreArg_byte = 0;
  cmock_call_instance->ReturnThruPtr_byte_Used = 0;
  cmock_call_instance->Expected_timeout_ms = timeout_ms;
  cmock_call_instance->IgnoreArg_timeout_ms = 0;
}

void uart3_getchar_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_getchar_CALL_INSTANCE));
  CMOCK_uart3_getchar_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_getchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_getchar_CallInstance = CMock_Guts_MemChain(Mock.uart3_getchar_CallInstance, cmock_guts_index);
  Mock.uart3_getchar_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.uart3_getchar_IgnoreBool = (int)1;
}

void uart3_getchar_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_getchar_CALL_INSTANCE));
  CMOCK_uart3_getchar_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_getchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_getchar_CallInstance = CMock_Guts_MemChain(Mock.uart3_getchar_CallInstance, cmock_guts_index);
  Mock.uart3_getchar_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void uart3_getchar_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* byte, uint32_t timeout_ms, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_getchar_CALL_INSTANCE));
  CMOCK_uart3_getchar_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_getchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_getchar_CallInstance = CMock_Guts_MemChain(Mock.uart3_getchar_CallInstance, cmock_guts_index);
  Mock.uart3_getchar_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_uart3_getchar(cmock_call_instance, byte, timeout_ms);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void uart3_getchar_StubWithCallback(CMOCK_uart3_getchar_CALLBACK Callback)
{
  Mock.uart3_getchar_IgnoreBool = (int)0;
  Mock.uart3_getchar_CallbackFunctionPointer = Callback;
}

void uart3_getchar_CMockReturnMemThruPtr_byte(UNITY_LINE_TYPE cmock_line, char* byte, int cmock_size)
{
  CMOCK_uart3_getchar_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_getchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_getchar_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_byte_Used = 1;
  cmock_call_instance->ReturnThruPtr_byte_Val = byte;
  cmock_call_instance->ReturnThruPtr_byte_Size = cmock_size;
}

void uart3_getchar_CMockIgnoreArg_byte(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart3_getchar_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_getchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_getchar_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_byte = 1;
}

void uart3_getchar_CMockIgnoreArg_timeout_ms(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart3_getchar_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_getchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_getchar_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timeout_ms = 1;
}

bool uart3_init(unsigned int baudRate, int rxQSize, int txQSize)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart3_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart3_init);
  cmock_call_instance = (CMOCK_uart3_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart3_init_CallInstance);
  Mock.uart3_init_CallInstance = CMock_Guts_MemNext(Mock.uart3_init_CallInstance);
  if (Mock.uart3_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.uart3_init_FinalReturn;
    Mock.uart3_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.uart3_init_CallbackFunctionPointer != NULL)
  {
    return Mock.uart3_init_CallbackFunctionPointer(baudRate, rxQSize, txQSize, Mock.uart3_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_baudRate)
  {
    UNITY_SET_DETAILS(CMockString_uart3_init,CMockString_baudRate);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_baudRate, baudRate, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_rxQSize)
  {
    UNITY_SET_DETAILS(CMockString_uart3_init,CMockString_rxQSize);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_rxQSize, rxQSize, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_txQSize)
  {
    UNITY_SET_DETAILS(CMockString_uart3_init,CMockString_txQSize);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_txQSize, txQSize, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart3_init(CMOCK_uart3_init_CALL_INSTANCE* cmock_call_instance, unsigned int baudRate, int rxQSize, int txQSize)
{
  cmock_call_instance->Expected_baudRate = baudRate;
  cmock_call_instance->IgnoreArg_baudRate = 0;
  cmock_call_instance->Expected_rxQSize = rxQSize;
  cmock_call_instance->IgnoreArg_rxQSize = 0;
  cmock_call_instance->Expected_txQSize = txQSize;
  cmock_call_instance->IgnoreArg_txQSize = 0;
}

void uart3_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_init_CALL_INSTANCE));
  CMOCK_uart3_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_init_CallInstance = CMock_Guts_MemChain(Mock.uart3_init_CallInstance, cmock_guts_index);
  Mock.uart3_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.uart3_init_IgnoreBool = (int)1;
}

void uart3_init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_init_CALL_INSTANCE));
  CMOCK_uart3_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_init_CallInstance = CMock_Guts_MemChain(Mock.uart3_init_CallInstance, cmock_guts_index);
  Mock.uart3_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void uart3_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int baudRate, int rxQSize, int txQSize, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_init_CALL_INSTANCE));
  CMOCK_uart3_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_init_CallInstance = CMock_Guts_MemChain(Mock.uart3_init_CallInstance, cmock_guts_index);
  Mock.uart3_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_uart3_init(cmock_call_instance, baudRate, rxQSize, txQSize);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void uart3_init_StubWithCallback(CMOCK_uart3_init_CALLBACK Callback)
{
  Mock.uart3_init_IgnoreBool = (int)0;
  Mock.uart3_init_CallbackFunctionPointer = Callback;
}

void uart3_init_CMockIgnoreArg_baudRate(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart3_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_baudRate = 1;
}

void uart3_init_CMockIgnoreArg_rxQSize(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart3_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_rxQSize = 1;
}

void uart3_init_CMockIgnoreArg_txQSize(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart3_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_txQSize = 1;
}

bool uart3_gets(char* pBuff, int maxLen, unsigned int timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart3_gets_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart3_gets);
  cmock_call_instance = (CMOCK_uart3_gets_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart3_gets_CallInstance);
  Mock.uart3_gets_CallInstance = CMock_Guts_MemNext(Mock.uart3_gets_CallInstance);
  if (Mock.uart3_gets_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.uart3_gets_FinalReturn;
    Mock.uart3_gets_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.uart3_gets_CallbackFunctionPointer != NULL)
  {
    return Mock.uart3_gets_CallbackFunctionPointer(pBuff, maxLen, timeout, Mock.uart3_gets_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_pBuff)
  {
    UNITY_SET_DETAILS(CMockString_uart3_gets,CMockString_pBuff);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_pBuff, pBuff, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_maxLen)
  {
    UNITY_SET_DETAILS(CMockString_uart3_gets,CMockString_maxLen);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_maxLen, maxLen, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_timeout)
  {
    UNITY_SET_DETAILS(CMockString_uart3_gets,CMockString_timeout);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_timeout, timeout, cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ReturnThruPtr_pBuff_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(pBuff, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)pBuff, (void*)cmock_call_instance->ReturnThruPtr_pBuff_Val,
      cmock_call_instance->ReturnThruPtr_pBuff_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart3_gets(CMOCK_uart3_gets_CALL_INSTANCE* cmock_call_instance, char* pBuff, int maxLen, unsigned int timeout)
{
  cmock_call_instance->Expected_pBuff = pBuff;
  cmock_call_instance->IgnoreArg_pBuff = 0;
  cmock_call_instance->ReturnThruPtr_pBuff_Used = 0;
  cmock_call_instance->Expected_maxLen = maxLen;
  cmock_call_instance->IgnoreArg_maxLen = 0;
  cmock_call_instance->Expected_timeout = timeout;
  cmock_call_instance->IgnoreArg_timeout = 0;
}

void uart3_gets_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_gets_CALL_INSTANCE));
  CMOCK_uart3_gets_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_gets_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_gets_CallInstance = CMock_Guts_MemChain(Mock.uart3_gets_CallInstance, cmock_guts_index);
  Mock.uart3_gets_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.uart3_gets_IgnoreBool = (int)1;
}

void uart3_gets_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_gets_CALL_INSTANCE));
  CMOCK_uart3_gets_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_gets_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_gets_CallInstance = CMock_Guts_MemChain(Mock.uart3_gets_CallInstance, cmock_guts_index);
  Mock.uart3_gets_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void uart3_gets_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* pBuff, int maxLen, unsigned int timeout, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_gets_CALL_INSTANCE));
  CMOCK_uart3_gets_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_gets_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_gets_CallInstance = CMock_Guts_MemChain(Mock.uart3_gets_CallInstance, cmock_guts_index);
  Mock.uart3_gets_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_uart3_gets(cmock_call_instance, pBuff, maxLen, timeout);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void uart3_gets_StubWithCallback(CMOCK_uart3_gets_CALLBACK Callback)
{
  Mock.uart3_gets_IgnoreBool = (int)0;
  Mock.uart3_gets_CallbackFunctionPointer = Callback;
}

void uart3_gets_CMockReturnMemThruPtr_pBuff(UNITY_LINE_TYPE cmock_line, char* pBuff, int cmock_size)
{
  CMOCK_uart3_gets_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_gets_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_gets_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pBuff_Used = 1;
  cmock_call_instance->ReturnThruPtr_pBuff_Val = pBuff;
  cmock_call_instance->ReturnThruPtr_pBuff_Size = cmock_size;
}

void uart3_gets_CMockIgnoreArg_pBuff(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart3_gets_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_gets_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_gets_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pBuff = 1;
}

void uart3_gets_CMockIgnoreArg_maxLen(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart3_gets_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_gets_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_gets_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_maxLen = 1;
}

void uart3_gets_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart3_gets_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_gets_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_gets_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timeout = 1;
}

bool uart3_puts(const char* pString, unsigned int timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart3_puts_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart3_puts);
  cmock_call_instance = (CMOCK_uart3_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart3_puts_CallInstance);
  Mock.uart3_puts_CallInstance = CMock_Guts_MemNext(Mock.uart3_puts_CallInstance);
  if (Mock.uart3_puts_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.uart3_puts_FinalReturn;
    Mock.uart3_puts_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.uart3_puts_CallbackFunctionPointer != NULL)
  {
    return Mock.uart3_puts_CallbackFunctionPointer(pString, timeout, Mock.uart3_puts_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_pString)
  {
    UNITY_SET_DETAILS(CMockString_uart3_puts,CMockString_pString);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_pString, pString, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_timeout)
  {
    UNITY_SET_DETAILS(CMockString_uart3_puts,CMockString_timeout);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_timeout, timeout, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart3_puts(CMOCK_uart3_puts_CALL_INSTANCE* cmock_call_instance, const char* pString, unsigned int timeout)
{
  cmock_call_instance->Expected_pString = pString;
  cmock_call_instance->IgnoreArg_pString = 0;
  cmock_call_instance->Expected_timeout = timeout;
  cmock_call_instance->IgnoreArg_timeout = 0;
}

void uart3_puts_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_puts_CALL_INSTANCE));
  CMOCK_uart3_puts_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_puts_CallInstance = CMock_Guts_MemChain(Mock.uart3_puts_CallInstance, cmock_guts_index);
  Mock.uart3_puts_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.uart3_puts_IgnoreBool = (int)1;
}

void uart3_puts_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_puts_CALL_INSTANCE));
  CMOCK_uart3_puts_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_puts_CallInstance = CMock_Guts_MemChain(Mock.uart3_puts_CallInstance, cmock_guts_index);
  Mock.uart3_puts_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void uart3_puts_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* pString, unsigned int timeout, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_puts_CALL_INSTANCE));
  CMOCK_uart3_puts_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_puts_CallInstance = CMock_Guts_MemChain(Mock.uart3_puts_CallInstance, cmock_guts_index);
  Mock.uart3_puts_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_uart3_puts(cmock_call_instance, pString, timeout);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void uart3_puts_StubWithCallback(CMOCK_uart3_puts_CALLBACK Callback)
{
  Mock.uart3_puts_IgnoreBool = (int)0;
  Mock.uart3_puts_CallbackFunctionPointer = Callback;
}

void uart3_puts_CMockIgnoreArg_pString(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart3_puts_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_puts_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pString = 1;
}

void uart3_puts_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uart3_puts_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uart3_puts_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timeout = 1;
}

