/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockbit_count.h"

static const char* CMockString_bit_count_get_uint8 = "bit_count_get_uint8";
static const char* CMockString_value = "value";

typedef struct _CMOCK_bit_count_get_uint8_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t ReturnVal;
  uint8_t Expected_value;
  int IgnoreArg_value;

} CMOCK_bit_count_get_uint8_CALL_INSTANCE;

static struct Mockbit_countInstance
{
  int bit_count_get_uint8_IgnoreBool;
  uint32_t bit_count_get_uint8_FinalReturn;
  CMOCK_bit_count_get_uint8_CALLBACK bit_count_get_uint8_CallbackFunctionPointer;
  int bit_count_get_uint8_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE bit_count_get_uint8_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockbit_count_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.bit_count_get_uint8_IgnoreBool)
    Mock.bit_count_get_uint8_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_bit_count_get_uint8);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.bit_count_get_uint8_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.bit_count_get_uint8_CallbackFunctionPointer != NULL)
    Mock.bit_count_get_uint8_CallInstance = CMOCK_GUTS_NONE;
}

void Mockbit_count_Init(void)
{
  Mockbit_count_Destroy();
}

void Mockbit_count_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.bit_count_get_uint8_CallbackFunctionPointer = NULL;
  Mock.bit_count_get_uint8_CallbackCalls = 0;
}

uint32_t bit_count_get_uint8(uint8_t value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_bit_count_get_uint8_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_bit_count_get_uint8);
  cmock_call_instance = (CMOCK_bit_count_get_uint8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.bit_count_get_uint8_CallInstance);
  Mock.bit_count_get_uint8_CallInstance = CMock_Guts_MemNext(Mock.bit_count_get_uint8_CallInstance);
  if (Mock.bit_count_get_uint8_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.bit_count_get_uint8_FinalReturn;
    Mock.bit_count_get_uint8_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.bit_count_get_uint8_CallbackFunctionPointer != NULL)
  {
    return Mock.bit_count_get_uint8_CallbackFunctionPointer(value, Mock.bit_count_get_uint8_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_value)
  {
    UNITY_SET_DETAILS(CMockString_bit_count_get_uint8,CMockString_value);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_value, value, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_bit_count_get_uint8(CMOCK_bit_count_get_uint8_CALL_INSTANCE* cmock_call_instance, uint8_t value)
{
  cmock_call_instance->Expected_value = value;
  cmock_call_instance->IgnoreArg_value = 0;
}

void bit_count_get_uint8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_bit_count_get_uint8_CALL_INSTANCE));
  CMOCK_bit_count_get_uint8_CALL_INSTANCE* cmock_call_instance = (CMOCK_bit_count_get_uint8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.bit_count_get_uint8_CallInstance = CMock_Guts_MemChain(Mock.bit_count_get_uint8_CallInstance, cmock_guts_index);
  Mock.bit_count_get_uint8_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.bit_count_get_uint8_IgnoreBool = (int)1;
}

void bit_count_get_uint8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_bit_count_get_uint8_CALL_INSTANCE));
  CMOCK_bit_count_get_uint8_CALL_INSTANCE* cmock_call_instance = (CMOCK_bit_count_get_uint8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.bit_count_get_uint8_CallInstance = CMock_Guts_MemChain(Mock.bit_count_get_uint8_CallInstance, cmock_guts_index);
  Mock.bit_count_get_uint8_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void bit_count_get_uint8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t value, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_bit_count_get_uint8_CALL_INSTANCE));
  CMOCK_bit_count_get_uint8_CALL_INSTANCE* cmock_call_instance = (CMOCK_bit_count_get_uint8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.bit_count_get_uint8_CallInstance = CMock_Guts_MemChain(Mock.bit_count_get_uint8_CallInstance, cmock_guts_index);
  Mock.bit_count_get_uint8_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_bit_count_get_uint8(cmock_call_instance, value);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void bit_count_get_uint8_StubWithCallback(CMOCK_bit_count_get_uint8_CALLBACK Callback)
{
  Mock.bit_count_get_uint8_IgnoreBool = (int)0;
  Mock.bit_count_get_uint8_CallbackFunctionPointer = Callback;
}

void bit_count_get_uint8_CMockIgnoreArg_value(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_bit_count_get_uint8_CALL_INSTANCE* cmock_call_instance = (CMOCK_bit_count_get_uint8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.bit_count_get_uint8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_value = 1;
}

