/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  CMock_Init(); \
  UNITY_CLR_DETAILS(); \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
    CMock_Verify(); \
  } \
  CMock_Destroy(); \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#ifdef __WIN32__
#define UNITY_INCLUDE_SETUP_STUBS
#endif
#include "unity.h"
#include "cmock.h"
#ifndef UNITY_EXCLUDE_SETJMP_H
#include <setjmp.h>
#endif
#include <stdio.h>
#include "c_period_callbacks.h"
#include <stdio.h>
#include "Mockc_uart2.h"
#include "Mockc_uart3.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_C_period_init(void);
extern void test_C_period_reg_tlm(void);
extern void test_C_period_1Hz(void);
extern void test_C_period_10Hz(void);
extern void test_C_period_100Hz(void);
extern void test_C_period_1000Hz(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  Mockc_uart2_Init();
  Mockc_uart3_Init();
}
static void CMock_Verify(void)
{
  Mockc_uart2_Verify();
  Mockc_uart3_Verify();
}
static void CMock_Destroy(void)
{
  Mockc_uart2_Destroy();
  Mockc_uart3_Destroy();
}

/*=======Suite Setup=====*/
static void suite_setup(void)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  suiteSetUp();
#endif
}

/*=======Suite Teardown=====*/
static int suite_teardown(int num_failures)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  return suiteTearDown(num_failures);
#else
  return num_failures;
#endif
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  CMock_Verify();
  CMock_Destroy();
  tearDown();
  CMock_Init();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  suite_setup();
  UnityBegin("code_test/test_period_callbacks.c");
  RUN_TEST(test_C_period_init, 15);
  RUN_TEST(test_C_period_reg_tlm, 20);
  RUN_TEST(test_C_period_1Hz, 24);
  RUN_TEST(test_C_period_10Hz, 28);
  RUN_TEST(test_C_period_100Hz, 32);
  RUN_TEST(test_C_period_1000Hz, 40);

  CMock_Guts_MemFreeFinal();
  return suite_teardown(UnityEnd());
}
